services:
  - type: web
    name: pointblank-market
    env: node
    region: frankfurt
    plan: free
    buildCommand: yarn && npx prisma generate && npx prisma db push --accept-data-loss && npx tsc && npx vite build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./prod.db
      - key: JWT_SECRET
        generateValue: true
